name: Bug Report
description: Report errors related to the book content or code
title: "Description"
labels: [bug]
assignees: rasbt
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. Please fill out the details below to help resolve it.

  - type: textarea
    id: bug_description
    attributes:
      label: Bug description
      description: A description of the issue.
      placeholder: |
        Please provide a description of what the bug or issue is.
    validations:
      required: true

  - type: dropdown
    id: operating_system
    attributes:
      label: What operating system are you using?
      description: If applicable, please select the operating system where you experienced this issue.
      options:
        - "Unknown"
        - "macOS"
        - "Linux"
        - "Windows"
    validations:
      required: False

  - type: dropdown
    id: compute_environment
    attributes:
      label: Where do you run your code?
      description: Please select the computing environment where you ran this code.
      options:
        - "Local (laptop, desktop)"
        - "Lightning AI Studio"
        - "Google Colab"
        - "Other cloud environment (AWS, Azure, GCP)"
    validations:
      required: False

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your Python environment via the environment by pasting the output of the following code:
        ```python
        import sys
        import torch

        print(f"Python version: {sys.version}")
        print(f"PyTorch version: {torch.__version__}")
        print(f"CUDA available: {torch.cuda.is_available()}")
        if torch.cuda.is_available():
            print(f"CUDA device: {torch.cuda.get_device_name(0)}")
            print(f"CUDA version: {torch.version.cuda}")
        print(f"Device count: {torch.cuda.device_count()}")
        ```
      value: |
        ```



        ```
    validations:
      required: false
